# Generated by Django 3.2.6 on 2021-08-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210826_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
